// Code generated by protoc-gen-go. DO NOT EDIT.
// source: healthproto.proto

package healthproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CodeServerStatus struct {
	Port                 int64    `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	State                string   `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	Url                  string   `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Alias                string   `protobuf:"bytes,4,opt,name=alias,proto3" json:"alias,omitempty"`
	AliasURL             string   `protobuf:"bytes,5,opt,name=aliasURL,proto3" json:"aliasURL,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CodeServerStatus) Reset()         { *m = CodeServerStatus{} }
func (m *CodeServerStatus) String() string { return proto.CompactTextString(m) }
func (*CodeServerStatus) ProtoMessage()    {}
func (*CodeServerStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_b205b526963b93a7, []int{0}
}

func (m *CodeServerStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CodeServerStatus.Unmarshal(m, b)
}
func (m *CodeServerStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CodeServerStatus.Marshal(b, m, deterministic)
}
func (m *CodeServerStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CodeServerStatus.Merge(m, src)
}
func (m *CodeServerStatus) XXX_Size() int {
	return xxx_messageInfo_CodeServerStatus.Size(m)
}
func (m *CodeServerStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_CodeServerStatus.DiscardUnknown(m)
}

var xxx_messageInfo_CodeServerStatus proto.InternalMessageInfo

func (m *CodeServerStatus) GetPort() int64 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *CodeServerStatus) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *CodeServerStatus) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *CodeServerStatus) GetAlias() string {
	if m != nil {
		return m.Alias
	}
	return ""
}

func (m *CodeServerStatus) GetAliasURL() string {
	if m != nil {
		return m.AliasURL
	}
	return ""
}

type HealthCheck struct {
	CodeServerProxy      string              `protobuf:"bytes,1,opt,name=codeServerProxy,proto3" json:"codeServerProxy,omitempty"`
	CodeServers          []*CodeServerStatus `protobuf:"bytes,2,rep,name=codeServers,proto3" json:"codeServers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *HealthCheck) Reset()         { *m = HealthCheck{} }
func (m *HealthCheck) String() string { return proto.CompactTextString(m) }
func (*HealthCheck) ProtoMessage()    {}
func (*HealthCheck) Descriptor() ([]byte, []int) {
	return fileDescriptor_b205b526963b93a7, []int{1}
}

func (m *HealthCheck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthCheck.Unmarshal(m, b)
}
func (m *HealthCheck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthCheck.Marshal(b, m, deterministic)
}
func (m *HealthCheck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthCheck.Merge(m, src)
}
func (m *HealthCheck) XXX_Size() int {
	return xxx_messageInfo_HealthCheck.Size(m)
}
func (m *HealthCheck) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthCheck.DiscardUnknown(m)
}

var xxx_messageInfo_HealthCheck proto.InternalMessageInfo

func (m *HealthCheck) GetCodeServerProxy() string {
	if m != nil {
		return m.CodeServerProxy
	}
	return ""
}

func (m *HealthCheck) GetCodeServers() []*CodeServerStatus {
	if m != nil {
		return m.CodeServers
	}
	return nil
}

func init() {
	proto.RegisterType((*CodeServerStatus)(nil), "healthproto.CodeServerStatus")
	proto.RegisterType((*HealthCheck)(nil), "healthproto.HealthCheck")
}

func init() { proto.RegisterFile("healthproto.proto", fileDescriptor_b205b526963b93a7) }

var fileDescriptor_b205b526963b93a7 = []byte{
	// 198 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xcc, 0x48, 0x4d, 0xcc,
	0x29, 0xc9, 0x28, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0x03, 0x93, 0x42, 0xdc, 0x48, 0x42, 0x4a, 0x0d,
	0x8c, 0x5c, 0x02, 0xce, 0xf9, 0x29, 0xa9, 0xc1, 0xa9, 0x45, 0x65, 0xa9, 0x45, 0xc1, 0x25, 0x89,
	0x25, 0xa5, 0xc5, 0x42, 0x42, 0x5c, 0x2c, 0x05, 0xf9, 0x45, 0x25, 0x12, 0x8c, 0x0a, 0x8c, 0x1a,
	0xcc, 0x41, 0x60, 0xb6, 0x90, 0x08, 0x17, 0x6b, 0x71, 0x49, 0x62, 0x49, 0xaa, 0x04, 0x93, 0x02,
	0xa3, 0x06, 0x67, 0x10, 0x84, 0x23, 0x24, 0xc0, 0xc5, 0x5c, 0x5a, 0x94, 0x23, 0xc1, 0x0c, 0x16,
	0x03, 0x31, 0x41, 0xea, 0x12, 0x73, 0x32, 0x13, 0x8b, 0x25, 0x58, 0x20, 0xea, 0xc0, 0x1c, 0x21,
	0x29, 0x2e, 0x0e, 0x30, 0x23, 0x34, 0xc8, 0x47, 0x82, 0x15, 0x2c, 0x01, 0xe7, 0x2b, 0x55, 0x70,
	0x71, 0x7b, 0x80, 0x5d, 0xe4, 0x9c, 0x91, 0x9a, 0x9c, 0x2d, 0xa4, 0xc1, 0xc5, 0x9f, 0x0c, 0x77,
	0x50, 0x40, 0x51, 0x7e, 0x45, 0x25, 0xd8, 0x1d, 0x9c, 0x41, 0xe8, 0xc2, 0x42, 0xf6, 0x5c, 0xdc,
	0x08, 0xa1, 0x62, 0x09, 0x26, 0x05, 0x66, 0x0d, 0x6e, 0x23, 0x59, 0x3d, 0x64, 0x1f, 0xa3, 0x7b,
	0x2d, 0x08, 0x59, 0x47, 0x12, 0x1b, 0x58, 0x91, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xf3, 0x04,
	0xc8, 0x4b, 0x25, 0x01, 0x00, 0x00,
}
